### ISSUE TITLE
Issue on page /11_tei_BS.html

### ISSUE THREAD

**Issue by lb42** [KBNLresearch/xml-workshop#2]
I was puzzled by the statement that there is no TEI namespace when I read through this tutorial very quickly. But then I looked here and saw that your texts are using a VERY old version of TEI -- specifically P3, support for which was officially withdrawn nearly ten years ago! Are there plans to update  to a more recent version any time soon? You should at least warn people that the tools you describe will need adapting to work properly with more recent versions of TEI (which do of course have a namespace)

**Comment by MirjamC** [comment]
Thank you for your response. The statement about the missing namespaces in TEI are based on the TEI files used in this course. Although these are old versions, we have still lots of material in this format as when they where digitized, this was the available format. When newer formats are available, these will likely be used for the material digitized from then on. The tutorial gives plenty of information about how to deal with namespaces in other parts, so when someone comes across a TEI with namespaces, they should be able to work with them without a problem.
